module.exports = {
  title: 'AIエージェントと学ぶ バイオインフォマティクスプログラミングの作法',
  author: '二階堂 愛',
  language: 'ja',
  size: '182mm 257mm',
  theme: '@vivliostyle/theme-techbook',
  entry: [
    'chapters/hajimeni.md',
    'chapters/00_ai_agent.md',
    'chapters/01_design.md',
    'chapters/02_terminal.md',
    'chapters/03_cs_basics.md',
    'chapters/04_data_formats.md',
    'chapters/05_software_components.md',
    'chapters/06_dev_environment.md',
    'chapters/07_git.md',
    'chapters/08_testing.md',
    'chapters/09_debug.md',
    'chapters/10_deliverables.md',
    'chapters/11_cli.md',
    'chapters/12_data_processing.md',
    'chapters/13_visualization.md',
    'chapters/14_workflow.md',
    'chapters/15_container.md',
    'chapters/16_hpc.md',
    'chapters/17_performance.md',
    'chapters/18_documentation.md',
    'chapters/19_database_api.md',
    'chapters/20_security_ethics.md',
    'chapters/21_collaboration.md',
    'chapters/appendix_a_learning_patterns.md',
    'chapters/appendix_b_cli_reference.md',
    'chapters/appendix_c_checklist.md',
    'chapters/appendix_d_agent_vocabulary.md',
    'chapters/glossary.md',
    'chapters/author.md',
  ],
  output: [
    'build/ai-biocode-kata-vivliostyle.pdf',
  ],
};
